name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/config/config.ini
      - TOTAL_CLIENTS=5
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config/config.ini:ro

    stop_signal: SIGTERM          # señal que se envía al detener
    stop_grace_period: 5s         # tiempo para que haga shutdown limpio
    restart: "on-failure:3"       # reintenta hasta 3 veces si muere con exit != 0

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CONFIG_FILE=/config/config.yaml
      - DATA_FILE=/data/agency.csv
    volumes:
      - ./client/config.yaml:/config/config.yaml:ro
      - ./.data/agency-1.csv:/data/agency.csv:ro
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CONFIG_FILE=/config/config.yaml
      - DATA_FILE=/data/agency.csv
    volumes:
      - ./client/config.yaml:/config/config.yaml:ro
      - ./.data/agency-2.csv:/data/agency.csv:ro
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CONFIG_FILE=/config/config.yaml
      - DATA_FILE=/data/agency.csv
    volumes:
      - ./client/config.yaml:/config/config.yaml:ro
      - ./.data/agency-3.csv:/data/agency.csv:ro
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CONFIG_FILE=/config/config.yaml
      - DATA_FILE=/data/agency.csv
    volumes:
      - ./client/config.yaml:/config/config.yaml:ro
      - ./.data/agency-4.csv:/data/agency.csv:ro
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CONFIG_FILE=/config/config.yaml
      - DATA_FILE=/data/agency.csv
    volumes:
      - ./client/config.yaml:/config/config.yaml:ro
      - ./.data/agency-5.csv:/data/agency.csv:ro
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
